### ISSUE TITLE
Have tank respond to coordinator with JSON objects

### ISSUE THREAD

**Issue by zjc2106** [Barnard-PL-Labs/esp32-tanks#9]
[X] Update the tank's responses to the coordinator to be JSON objects instead of strings
[X] Make sure all other network communication is JSON objects

**Comment by faustinacheng** [comment]
- Added `function` field to sent command JSON, with the other required fields dependent on what the function is
- Updated tank's responses to the coordinator to be JSON objects instead of strings
Commit: [de1593f](https://github.com/Barnard-PL-Labs/esp32-tanks/commit/de1593f56b6b3bc74c574c39c827e9076bf623e8)

See below on how the packets are structured now:

## Packet Structure

### Sent Commands

Sent commands are in JSON format, where the `function` field can be:

- [`motor`](#motor): To move the tank
- [`light`](#light): To adjust the headlight
- [`camera`](#camera): To control the camera

Each of these functions have their own required fields:

#### `motor` <a name="motor"></a>

- `direction`: `l`/`r`/`f`/`b` to denote the direction the tank should go (respectively, left, right, forward, backwards)
- `value`: degrees for l,r and milliseconds for f,b

Example:

```json
{
  "function": "motor",
  "direction": "f",
  "value": "1000"
}
```

#### `light` (TBD) <a name="light"></a>

- `value`: range from 0 = off to ??? = full brightness

#### `camera` (TBD) <a name="camera"></a>

TBD



Note: Commands should be entered via the serial in the form: `[function] <required fields>`, where the required fields follow the order specified above. 

### Responses

Responses are also in JSON format, with the fields:

- `status`: `success` or `error` 
- `message`: for a detailed message of the command executed

Example:

```json
{
	"status": "success",
	"message":
}
```

Will add the above as a doc in communication/README.md
